### ISSUE TITLE
HTTP output plugin causes RPi crash after long time periods

### ISSUE THREAD

**Issue by haydnw** [haydnw/AirPi#12]
Enabling the HTTP output plugin has been shown to cause the Raspberry Pi to crash after running for any length of time. There are no error messages or debug messages displayed. Cause is currently unknown.

**Comment by bugs78** [comment]
Hi I have installed the latest version in GitHub, and when I run it with HTTP I get the following

ERROR: Did not import output plugin HTTP:__init__() takes exactly 2 arguments (3 given)
Traceback (most recent call last):
               File "/home/pi/AirPi/airpi.py", line 1254, in <module>
                           PLUGINSOUTPUTS = set_up_outputs()
               File "/home/pi/airpi.py", line 540, in set_up_outputs
                           raise excep
TypeError:__init__() takes exactly 2 arguments (3 given)

Hope this helps
